### ISSUE TITLE
Locales de are actually locales nl

### ISSUE THREAD

**Issue by Angeal87** [justverifyit/thunderbird#11]
The language files for DE are wrong. Dutch texts have been inserted here. But they should have been German texts.

**Comment by nicprov** [comment]
@Angeal87 Unless I'm mistaken, DE is for Dutch, not German. From what I can tell Thunderbird does not support German specifically, they only support Dutch.

You can verify this for yourself on their website (which uses the same standard). You can verify this here (if you look at the bottom it says Deutsch): https://addons.thunderbird.net/de/thunderbird/
<img width="259" alt="image" src="https://github.com/justverifyit/thunderbird/assets/66100220/4189d379-2fcf-472d-91ba-383388f678a2">

**Comment by nicprov** [comment]
@Angeal87 I will correct this.
