### ISSUE TITLE
Better explanation of how "just verify it" works

### ISSUE THREAD

**Issue by ghost** [justverifyit/thunderbird#25]
Hi,
according to

https://addons.thunderbird.net/it/thunderbird/addon/just-verify-it

> Just Verify It is a powerful and efficient Thunderbird add-on that automatically uploads all email attachments to VirusTotal

https://justverify.it

> Just Verify It is a Thunderbird add-on that automatically scans all email attachments with VirusTotal

so I understand that "Just Verify It" will upload every attachment of my email regardless of my actions. However, when I open an email I have to press "Verify It" button to have it checked.

This behaviour is expected, since I do not want to send every attachment to Virus Total without my confirmation, but instructions are not clear enough on how the process is handled

**Comment by nicprov** [comment]
@AnthillSudoku Thanks for the heads up, that description is not accurate, I will update it to make it more clear. It doesn't automatically upload all email attachments so you are right for that. It will only upload email attachments for messages when you click the "Verify It" button.
